app = "chat-app-frontend"

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "80"

[[services]]
  internal_port = 80
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"

[mounts]
  source = "static"
  destination = "/usr/share/nginx/html"
